# Note: when updating this file, you may also need
# to update other stack-*.yaml files.

resolver: lts-18.10

packages:
  - core
  - simple
  - full

extra-deps:
- git: https://github.com/Martoon-00/tasty-discover.git
  commit: 43bed101756befbfeba046a89b92d14cfbb321b2
